services:
#    visualiser.example:
#        class: visualiserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
visualiser.todolist:
    class: visualiserBundle\Model\ToDoList
