services:
    visualiser.todolist:
        class: VisualiserBundle\Model\ToDoList
        arguments: ['@visualiser.fileLocator']
    visualiser.fileLocator:
        class: Symfony\Component\Config\FileLocator
